# Generated by Django 6.1.1 on 2026-09-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('demand_level', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.PositiveSmallIntegerField(default=3)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_skills', to='careers.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_links', to='skills.skill')),
            ],
            options={
                'unique_together': {('career', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.ManyToManyField(related_name='careers', through='careers.CareerSkill', to='skills.skill'),
        ),
    ]
